version: '3'

volumes:
  website_v2_local_postgres_data: {}
  website_v2_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: website_v2_local_django
    container_name: website_v2_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '5008:5008'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: website_v2_production_postgres
    container_name: website_v2_local_postgres
    volumes:
      - website_v2_local_postgres_data:/var/lib/postgresql/data
      - website_v2_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: website_v2_local_docs
    container_name: website_v2_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./website_v2:/app/website_v2:z
    ports:
      - '9000:9000'
    command: /start-docs
